<<<<<<< HEAD
import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;

import javax.swing.JOptionPane;

public class GUIHorarios extends javax.swing.JDialog {

    private Medico medico;
    private String nomeCliente;
    private final String nomeMedico;
    private final String especialidade;
    
    public GUIHorarios(java.awt.Frame parent, boolean modal, Medico medico, String nomeCliente, String especialidade, String nomeMedico) {
        super(parent, modal);
        initComponents();
        this.medico = medico;
        System.out.println(this.medico.getAgenda());
        this.nomeCliente = nomeCliente;
        this.nomeMedico = nomeMedico;
        this.especialidade = especialidade;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jComboBox4 = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setPreferredSize(new java.awt.Dimension(364, 143));
=======
>>>>>>> 7bbaae65bb28a5c6bf50908f2137d8bb420cf7b9


import java.awt.BorderLayout;
import java.awt.EventQueue;

import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.border.EmptyBorder;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import java.awt.Font;
import javax.swing.JComboBox;
import javax.swing.JButton;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.awt.event.ActionEvent;

public class GUIHorarios extends JFrame {

	private JPanel contentPane;
	private Boolean aprovado;
	/**
	 * Create the frame.
	 */
	public GUIHorarios(Medico medico) {
		setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
		setBounds(100, 100, 450, 222);
		contentPane = new JPanel();
		contentPane.setBorder(new EmptyBorder(5, 5, 5, 5));
		setContentPane(contentPane);
		contentPane.setLayout(null);
		
		JLabel lblNewLabel = new JLabel("SELECAO DE HORARIO");
		lblNewLabel.setFont(new Font("Tahoma", Font.BOLD, 12));
		lblNewLabel.setHorizontalAlignment(SwingConstants.CENTER);
		lblNewLabel.setBounds(10, 11, 414, 14);
		contentPane.add(lblNewLabel);
		
		JLabel lblSelecioneODia = new JLabel("Selecione o dia:");
		lblSelecioneODia.setBounds(10, 39, 136, 14);
		contentPane.add(lblSelecioneODia);
		

		JLabel lblSelecioneOHoraroi = new JLabel("Selecione o horario:");
		lblSelecioneOHoraroi.setBounds(10, 70, 136, 14);
		contentPane.add(lblSelecioneOHoraroi);
		
		JComboBox<String> comboBox_1 = new JComboBox<String>();
		comboBox_1.setBounds(142, 67, 282, 20);
		contentPane.add(comboBox_1);
		
		JComboBox<String> comboBox = new JComboBox<String>();
		comboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione o dia", "2", "3", "4", "5", "6", "9", "10", "11", "12", "13", "16", "17", "18", "19", "20", "23", "24", "25", "26", "27", "30" }));
		comboBox.setBounds(142, 36, 282, 20);
		contentPane.add(comboBox);
		comboBox.addActionListener(new java.awt.event.ActionListener() {
        	public void actionPerformed(java.awt.event.ActionEvent evt) {
            	ArrayList<Horario> listaHorarios = new ArrayList<Horario>();
            	comboBox_1.removeAllItems();
            	try {
            		listaHorarios = medico.getAgenda().getDataPorDia(Integer.parseInt(comboBox.getSelectedItem().toString())).getListaHorarios();
            	} catch(NumberFormatException e) {
        			JOptionPane.showMessageDialog(null, "Por favor selecione um dia válido");
            	} catch(NullPointerException e) {
            		comboBox_1.addItem("Nenhum horario disponivel");
            	}
            	if(listaHorarios != null) {
            		for(int i = 0; i < listaHorarios.size(); i++) {
            			if(listaHorarios.get(i).isDisponivel())
            				comboBox_1.addItem(listaHorarios.get(i).getHora());
            	    }   
            	}
            }
<<<<<<< HEAD
        });
        
        
        jLabel5.setText("Metodo de pagamento");
        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "Cortesia", "Dinheiro", "Cartao", "Cheque" }));
        jComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
            	jComboBox4.removeAllItems();
            	if(!jComboBox3.getSelectedItem().toString().equals("Cortesia")) {
            		jComboBox4.addItem("Particular");
            		jComboBox4.addItem("Convenio");
            	}
            }
        });

       
        jLabel4.setText("Tipo de Atendimento");
        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "Particular", "Convenio" }));
        jComboBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(24, 24, 24))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel2.setLayout(new java.awt.GridLayout(1, 0));

        jButton2.setText("Cancelar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2);

        jButton3.setText("Confirmar Consulta");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
            	TiposAutorizacao autorizacao = new TiposAutorizacao();
            	if(jComboBox3.getSelectedItem().toString().equals("Cortesia")) {
            		if(autorizacao.autorizaCortesia()) {
    					JOptionPane.showMessageDialog(null, "Agendamento realizado com sucesso!");
                                            salvaConsulta(nomeCliente, nomeMedico, especialidade, jComboBox1.getSelectedItem().toString(), jComboBox2.getSelectedItem().toString(), jComboBox3.getSelectedItem().toString());
    					setVisible(false);
=======
		});
		
		JLabel lblMetodoDePagamento = new JLabel("Metodo de Pagamento:");
		lblMetodoDePagamento.setBounds(10, 101, 136, 14);
		contentPane.add(lblMetodoDePagamento);
		
		JComboBox<String> comboBox_2 = new JComboBox<String>();
		comboBox_2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "Cortesia", "Dinheiro", "Cartão", "Cheque" , "Convenio"}));
		comboBox_2.setBounds(142, 98, 282, 20);
		contentPane.add(comboBox_2);
		
		JButton btnNewButton = new JButton("Cancelar");
		btnNewButton.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent arg0) {
				setVisible(false);
				dispose();
			}
		});
		btnNewButton.setBounds(0, 145, 212, 46);
		contentPane.add(btnNewButton);
		
		JButton btnConfirmarConsulta = new JButton("Confirmar Consulta");
		btnConfirmarConsulta.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				if(!comboBox.getSelectedItem().equals("Selecione o dia") && !comboBox_1.getSelectedItem().equals("") && !comboBox_2.getSelectedItem().equals("")) {
					TiposAutorizacao autorizacao = new TiposAutorizacao();
					
	            	if(comboBox_2.getSelectedItem().toString().equals("Cortesia")) {
	            		aprovado = autorizacao.autorizaCortesia();
	            	} else if(comboBox_2.getSelectedItem().equals("Cartão")) {
	            		aprovado = autorizacao.autorizaCartao();
	            	} else if(comboBox_2.getSelectedItem().equals("Dinheiro")) {
	            		aprovado = autorizacao.autorizaDinheiro();
	            	} else if(comboBox_2.getSelectedItem().equals("Convenio")) {
	            		aprovado = autorizacao.autorizaConvenio();
	            	} else {
	            		aprovado = autorizacao.autorizaConvenio();
	            	}
	            	
	            	if(aprovado) { 
	            		JOptionPane.showMessageDialog(null, "Agendamento realizado com sucesso!");
						setVisible(false);
>>>>>>> 7bbaae65bb28a5c6bf50908f2137d8bb420cf7b9
						dispose();
	            	} else {
	        			JOptionPane.showMessageDialog(null, "Agendamento não autorizado");
						setVisible(false);
						dispose();
<<<<<<< HEAD
            		}
            	} else if(jComboBox3.getSelectedItem().equals("Cartao")) {
            		
            	}
            }
           
        });
        jPanel2.add(jButton3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 442, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        setVisible(false);
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox3ActionPerformed

    private void jComboBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox4ActionPerformed
    
    public void salvaConsulta(String nomeCliente, String nomeMedico, String especialidade, String dia, String horario, String atendimento){
        try {
            FileWriter arq;
            arq = new FileWriter("Consultas", true);
            BufferedWriter bw = new BufferedWriter(arq);
            bw.write("Nome Cliente: " + nomeCliente);
            bw.newLine();
            bw.write("Nome Medico: " + nomeMedico);
            bw.newLine();
            bw.write("Especialidade: " + especialidade);
            bw.newLine();
            bw.write("Dia: " + dia);
            bw.newLine();
            bw.write("Horario: " + horario);
            bw.newLine();
            bw.write("Tipo de Atendimento: " + atendimento);
            bw.newLine();
            bw.write(",");
            bw.newLine();
            bw.close();
        } catch (IOException e) {
            JOptionPane.showMessageDialog(null, "Erro ao gravar a consulta!");
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
=======
	        		}
				} else {
					JOptionPane.showMessageDialog(null, "Por favor preencha todos os campos");
				}
				
			}
		});
		
		
		btnConfirmarConsulta.setBounds(209, 145, 225, 46);
		contentPane.add(btnConfirmarConsulta);
	}
>>>>>>> 7bbaae65bb28a5c6bf50908f2137d8bb420cf7b9
}
